# Generated by Django 2.2.7 on 2019-11-10 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='workers_cpf',
            new_name='workers',
        ),
        migrations.AddField(
            model_name='workers',
            name='adress',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='jobs.Adress'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workers',
            name='email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workers',
            name='name',
            field=models.CharField(default=0, max_length=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workers',
            name='passwork',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workers',
            name='surname',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('description', models.TextField(blank=True)),
                ('workers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Workers')),
            ],
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.CharField(max_length=250)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Project')),
            ],
        ),
    ]
