# Generated by Django 2.2.7 on 2019-11-11 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20191110_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='countClick',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
